name: CI
on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
    linux_clang:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - uses: actions/setup-python@v1
          with:
            python-version: '3.x'
        - run: pip install meson ninja
        - run: meson setup builddir/
          env:
            CC: clang
            CXX: clang++
        - run: meson test -C builddir/ -v
        - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: Linux_Meson_Testlog
            path: builddir/meson-logs/testlog.txt

    linux_gcc:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - uses: actions/setup-python@v1
          with:
            python-version: '3.x'
        - run: pip install meson ninja
        - run: meson setup builddir/
          env:
            CC: gcc
            CXX: g++
        - run: meson test -C builddir/ -v
        - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: Linux_Meson_Testlog
            path: builddir/meson-logs/testlog.txt

    macos:
      runs-on: macos-latest
      steps:
        - uses: actions/checkout@v1
        - uses: actions/setup-python@v1
          with:
            python-version: '3.x'
        - run: brew install gcc
        - run: pip install meson ninja
        - run: meson setup builddir/
          env:
            CC: gcc
        - run: meson test -C builddir/ -v
        - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: MacOS_Meson_Testlog
            path: builddir/meson-logs/testlog.txt
